### ISSUE TITLE
Non-async API?

### ISSUE THREAD

**Issue by seabassjh** [MOZGIII/xwt#138]
I want to use this crate on `wasm32-unknown-emscripten` but I see most of the API is async, and in emscripten, futures are not supported (well there is a compile flag called ASYNCIFY, but I've never gotten it work work, but that's outside of scope for this discussion). So I am hoping theres a way to use xwt without async. Thanks for your help!

**Comment by MOZGIII** [comment]
Currently there's no way I can think of to use `xwt` without async or futures - and I also am unaware of the issues that exit with emscripten.
Have you tired running the tests though? Maybe they'll just work. Or is it a compiler error?

Just for context, what's your use case for using emscripten builds? Why not native wasm?

**Comment by seabassjh** [comment]
Building a godot extension in rust that runs on WASM. Currently godot builds the engine and extension to WASM using emscripten

**Comment by seabassjh** [comment]
I'll try the tests in emscripten and report back to you!

**Comment by seabassjh** [comment]
Okay I cannot even invoke the entry point to the tests because simply the presence of any async call will panic on wasm32-unknown-unknown-emscripten.
``
wasm_bindgen_futures::spawn_local(async move {
     // initializing xwt in here
});
```
But of course this isn't xwt's problem :) it a me problem lol

**Comment by MOZGIII** [comment]
How do promises work with emscripten? The think is, it might be either simply unsupported, or straight up impossible - cause we have to use the promises for the actual I/O in wasm. If, for whatever reason, the promises can't work properly - say, like, we need thread parking support to wait for a delayed `.then` callback - and that causes blocking which is not allowed causes crash - then it's not even possible at all to have WebTransport API implemented.

> a godot extension in rust that runs on WASM

Does Godot provide this Web API though? Or is it for running Godot itself as a wasm build in the browser?
