### ISSUE TITLE
Reading from stream using AsyncRead doesn't work

### ISSUE THREAD

**Issue by vpzomtrrfrt** [MOZGIII/xwt#84]
(with xwt-web-sys)

e.g.
```rust
    let (mut send, mut recv) = connection
          .open_bi()
          .await
          .map_err(convert_error)?
          .wait_bi()
          .await?;

      send.write(b"test").await.map_err(convert_error)?;

      let mut buf = [0; 8];

      let amount = tokio::io::AsyncReadExt::read(&mut recv, &mut buf).await?;

      let value = &buf[..amount];
```

Fails with the error `{}` on reading.

Adding extra logging to web-sys-async-io, I was able to get this error instead:
```
TypeError: Failed to execute 'read' on 'ReadableStreamBYOBReader': parameter 1 is not of type 'ArrayBufferView'.
    at imports.wbg.__wbg_read_421ea09231f62999 (client.js:342:37)
    at web_sys::features::gen_ReadableStreamByobReader::ReadableStreamByobReader::read_with_array_buffer_view::h2d79409db104f874 (client_bg.wasm:0x192cf)
    at <web_sys_async_io::reader::Reader as tokio::io::async_read::AsyncRead>::poll_read::hc90cb112c785b849 (client_bg.wasm:0xc563)
    at <xwt_web_sys::RecvStream as tokio::io::async_read::AsyncRead>::poll_read::hfc44f7b8815e8db5 (client_bg.wasm:0x19294)
    at client::main::{{closure}}::haf584d15d6c74303 (client_bg.wasm:0x2561)
    at wasm_bindgen_futures::task::singlethread::Task::run::h0ab3b9ff943bdb36 (client_bg.wasm:0x15030)
    at wasm_bindgen_futures::queue::Queue::new::{{closure}}::h592219bb7764a2c3 (client_bg.wasm:0xf5c1)
    at wasm_bindgen::convert::closures::invoke1_mut::h00413c1a66bb61c2 (client_bg.wasm:0x18bc7)
    at __wbg_adapter_22 (client.js:208:10)
    at real (client.js:193:20)
```

**Comment by MOZGIII** [comment]
The test coverage is lacking in that area - the tokio bindings specifically. I can confirm it is likely broken on our end and should be fixed. As a workaround, you could use `xwt_core::io::Read::read` for now instead.

PRs are welcome.

**Comment by vpzomtrrfrt** [comment]
that isn't really feasible for me since I need to pass the stream to another library that expects an AsyncRead

**Comment by MOZGIII** [comment]
You might be able to quickly hack together a newtype and implement the tokio asyncread on top of `xwt_core::io::Read::read` - that is if the urgency of moving forward is important

**Comment by MOZGIII** [comment]
Wait, it's already like that, so it should work as it is tested, even in CI. What's your environment? Browser, etc

**Comment by vpzomtrrfrt** [comment]
they look pretty separate to me?

currently testing in Chromium 121.0.6167.139 on Arch Linux

**Comment by MOZGIII** [comment]
From your trace:
```
    at web_sys::features::gen_ReadableStreamByobReader::ReadableStreamByobReader::read_with_array_buffer_view::h2d79409db104f874 (client_bg.wasm:0x192cf)
    at <web_sys_async_io::reader::Reader as tokio::io::async_read::AsyncRead>::poll_read::hc90cb112c785b849 (client_bg.wasm:0xc563)
    at <xwt_web_sys::RecvStream as tokio::io::async_read::AsyncRead>::poll_read::hfc44f7b8815e8db5 (client_bg.wasm:0x19294)
```
They are already stacked one on top of the other.

**Comment by vpzomtrrfrt** [comment]
I don't see the xwt_core::io::Read implementation referencing either of the tokio impls or vice versa

**Comment by MOZGIII** [comment]
https://github.com/MOZGIII/xwt/blob/4a0bdf8b2650587725e79ca03f824e5dcca5a32a/crates/xwt-web-sys/src/lib.rs#L221-L229

and

https://github.com/MOZGIII/xwt/blob/4a0bdf8b2650587725e79ca03f824e5dcca5a32a/crates/xwt-web-sys/src/lib.rs#L91-L106

**Comment by vpzomtrrfrt** [comment]
```patch
diff --git a/crates/web-sys-async-io/src/reader.rs b/crates/web-sys-async-io/src/reader.rs
index 0298860..1157adf 100644
--- a/crates/web-sys-async-io/src/reader.rs
+++ b/crates/web-sys-async-io/src/reader.rs
@@ -68,18 +68,13 @@ impl tokio::io::AsyncRead for Reader {
                 Poll::Ready(Ok(()))
             }
             Op::Idle => {
-                let work_buf = match &mut self.internal_buf {
-                    Some(val) => val.buffer(),
-                    None => {
-                        let internal_buf =
-                            js_sys::Uint8Array::new_with_length(buf.capacity().try_into().unwrap());
-                        let view = internal_buf.buffer();
-                        self.internal_buf = Some(internal_buf);
-                        view
-                    }
-                };
+                let work_buf =
+                    js_sys::Uint8Array::new_with_length(buf.len().try_into().unwrap());
+
                 let fut = JsFuture::from(self.inner.read_with_array_buffer_view(&work_buf));
                 self.op = Op::Pending(fut);
+                self.internal_buf = Some(work_buf);
+
                 self.poll_read(cx, buf)
             }
         }
```

this seems like it resolves the issue but I don't understand this stuff enough to know if it breaks in other cases

**Comment by MOZGIII** [comment]
Could you create a repo with a minimal issue reproduction sample?

**Comment by vpzomtrrfrt** [comment]
Here's the code I've been testing with: https://git.sr.ht/~vpzom/xwt-issue-84

**Comment by MOZGIII** [comment]
How do I run it?

**Comment by vpzomtrrfrt** [comment]
with some difficulty 🙃

I don't know if there's a nice way to handle building wasm projects, I've added a Makefile now, which will put the build into target/wasm32-unknown-unknown/dist where it can be served from by a web server

To actually test it, one would need to get a valid TLS certificate for the server and change the URL in the client code to point at it

**Comment by vpzomtrrfrt** [comment]
also the extra issue I had is probably resolved by https://github.com/jonhoo/async-bincode/pull/22
